In [6]:
import numpy as np

In [7]:
a = np.random.randint(10, size = (5, 3, 3, 3))
b = np.random.randint(5, size = (27, 27))
c = np.random.randint(5, size = (27, ))

In [8]:
minibatch = a.shape[0]
k = a.reshape(minibatch, -1)
d = k@b
print(c.shape)

(27,)


In [9]:
kk = d+c
print(kk.shape)
kk = kk.reshape(a.shape)
print(kk.shape)
print((a*kk).shape)

(5, 27)
(5, 3, 3, 3)
(5, 3, 3, 3)


In [10]:
me = np.mean(k, axis = 0)
va = np.var(k, axis = 0).reshape(1, -1)
t = np.random.randint(5, size = (27, ))

In [11]:
print(me.shape)

(27,)


In [12]:
N = 3
D = 20

In [53]:
xx = np.random.randint(5, size = (N, D, D+4, D+5))
yy = np.random.randint(N, size = (N, D))
zz = np.random.randint(5, size = (D, N))
print(yy, zz)

[[0 1 1 0 2 1 0 0 2 2 1 2 2 2 0 2 2 0 2 2]
 [2 0 2 1 0 1 0 2 2 1 2 2 0 2 0 0 0 2 0 1]
 [1 0 1 2 2 1 0 0 1 0 1 1 0 0 0 2 2 2 2 0]] [[0 0 2]
 [2 0 0]
 [3 1 3]
 [2 0 1]
 [1 4 0]
 [1 3 3]
 [0 1 3]
 [4 1 0]
 [3 2 3]
 [2 1 4]
 [1 2 3]
 [4 1 1]
 [0 0 2]
 [0 3 4]
 [4 1 2]
 [1 1 0]
 [4 3 2]
 [1 4 0]
 [2 0 3]
 [3 2 3]]


In [14]:
np.sum(xx, axis = 0).shape

(20,)

In [15]:
idx = np.array_split(np.arange(D), 5)
vv = []
vv = yy[idx]
print(vv)

[[[0 1 1 2 1]
  [1 2 2 1 1]
  [1 0 2 1 2]
  [1 1 2 1 1]]

 [[1 2 1 2 0]
  [1 0 0 2 2]
  [1 1 2 1 2]
  [2 2 1 2 0]]

 [[1 2 1 1 2]
  [1 0 1 1 2]
  [2 1 2 0 2]
  [2 1 1 0 2]]

 [[0 0 2 2 2]
  [1 2 2 0 1]
  [2 0 2 0 1]
  [0 1 2 2 1]]

 [[2 0 1 0 2]
  [0 1 0 2 0]
  [1 1 0 2 2]
  [2 2 1 2 2]]]


In [ ]:
tt = np.zeros((2, 3))
tt[0 : ] = np.sum(np.square(yy - xx), axis = 1)
print(tt[0])

In [ ]:
np.argsort(tt[0])

In [ ]:
tv = np.random.randint(3, size = 10)
tv = np.append(tv, 4)

In [ ]:
tv[10 :]

In [ ]:
values, count = np.unique(tv, return_counts=True)

In [ ]:
print(2 * 4 ** 2)

In [ ]:
a = {1:2, 3:4}
print(len(a))

In [56]:
yy.reshape(zz.shape).shape

(20, 3)

In [3]:
import torch
a = torch.arange(1, 8)
print(2**a)

tensor([  2,   4,   8,  16,  32,  64, 128])
